const express = require('express');
const router = express.Router();
const { registerUser, loginUser, getUserProfile, getUserOrders, getUserStats, getSingleUser } = require("./user.controller");
const authMiddleware = require("../../middleware/auth.middleware");
router.post("/register", registerUser);
router.post("/login", loginUser);
router.get("/profile", authMiddleware, getUserProfile);
router.get("/orders", authMiddleware, getUserOrders);
router.get("/stats", authMiddleware, getUserStats);
router.get("/:id", authMiddleware, getSingleUser);
module.exports = router;